#!/bin/bash
export SRC_ROOT=`pwd`
export GTEST_ROOT=$SRC_ROOT/d_3rd/gtest-1.6.0
export LUA_ROOT=$SRC_ROOT/d_3rd/LuaJIT-2.0.1
export BOOST_ROOT=/usr/local/
export LIBEV_ROOT=/usr/local/
export JEMALLOC_ROOT=$SRC_ROOT/d_3rd/jemalloc-3.1.0


export LOG4CXX_LIB_PATH=/usr/local/lib

export LD_LIBRARY_PATH=$BOOST_ROOT/lib


